script: embeddings.py
# model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
model: infidelis/GigaChat-20B-A3B-instruct:q4_0
num_ctx: 22768
min_paragraph: 70
prefix_filter:
  - табл
  - рис
  - \|
plan: |
  Роль международного валютного фонда в регулировании международных валютно-финансовых отношений
  2 Теоретическая часть
  2.1 Регулирование международных валютно-финансовых отношений
  2.1.1 Исторический контекст и эволюция регулирования, ключевые события (Бреттон–Вудская конференция)
  2.1.1.1 Роль МВФ в формировании послевоенной международной финансовой архитектуры
  2.1.1.2 Переход к плавающим валютным курсам: конец золотого стандарта
  2.1.1.2.1 Распад Бреттон-Вудской системы и роль США в переходе
  2.1.1.2.2 Роль СДР после отказа от золотой основы
  2.1.2 Принципы современного международного финансового управления
  2.1.2.1 Виды операций в международном финансовом обороте 
  2.1.2.1.1 Глобальная торговля и её влияние на валютные курсы
  2.1.2.1.2 Интеграция офшорных зон
  2.1.2.1.3 Международное управление внешним долгом
  2.1.2.2 Монетарные и финансовые институты глобального уровня
  2.1.2.2.1 Роль ФРС, Банка Англии, Европейского Центробанка в валютном регулировании 
  2.1.2.2.2 Всемирный банк и взаимодействие с МВФ
  2.1.2.2.3 Региональные банки развития
  2.1.2.3 Системы валютного конвертирования: роль СДР (специальных прав заимствования)
  2.1.2.4 Монетарные стандарды и их эволюция
  2.1.2.5 Диверсификация мировых резервов, включая цифровые валюты
  2.1.2.5.1 Расширение роли юаня в мировой финансовой системе
  2.1.2.5.2 Роль золота как резервного актива
  2.2 Международный Валютный Фонд (МВФ)
  2.2.1 Структура и полномочия МВФ
  2.2.1.1 Формирование квот стран-членов и механизм голосования
  2.2.1.2 Административные процессы принятия решений в Фонде
  2.2.1.3 Финансовые ресурсы: пополнение резервных фондов, инвестиционные стратегии по регионам
  2.2.1.3.1 Интеграция цифровых активов и блокчейн технологий
  2.2.1.3.2 Роль МВФ в развитии инфраструктуры международных платежей
  2.2.2 Функции Фонда
  2.2.2.1 Поддержка мировой финансовой стабильности 
  2.2.2.1.1 Средства антикризисной помощи: кредитные программы, условия получения
  2.2.2.1.2 Мониторинг денежно-кредитных политик участников фонда
  2.2.2.1.3 Анализ глобальных экономических и политических рисков
  2.2.2.1.3.1 Геополитические риски и их оценка в Фонде
  2.2.2.2 Участие МВФ в макроэкономической политике стран – членов
  2.2.2.2.1 Консультации по денежно-кредитной политике
  2.2.2.2.2 Инфраструктура экономической помощи: кредитование, техническая поддержка реформ банковской системы и монетарной политики
  2.2.2.2.3 Мониторинг исполнения рекомендаций
  2.2.2.3 Экономический надзор
  2.2.2.3.1 Глубокий мониторинг тенденций мировой экономики
  2.2.2.3.2 Консультации для стран с рисками в торговле и платежном балансе
  2.2.2.3.3 Оценка вторичных эффектов экономической политики на мировую экономику
  2.2.2.4 Кредитование
  2.2.2.4.1 Нелеготное кредитование
  2.2.2.4.2 Лихтовое кредитование для стран с низким доходом
  2.2.2.4.3 Изменения в условиях и инструментах антикризисного финансирования
  2.2.2.5 Развитие потенциала государств-членов
  2.2.2.5.1 Обучение кадров, техническая поддержка реформ
  2.2.2.5.2 Поддержка мер по сокращению социального неравенства
  2.2.2.5.3 Программа повышения гендерного равенства в финансовой сфере
  2.2.2.6 Валютный контроль и международное сотрудничество
  2.2.2.6.1 Регулирование международных транзакций
  2.2.2.6.2 Сотрудничество с другими международными организациями (СФС, МВФ-ВБ альянс)
  2.2.3 Примеры антикризисных мероприятий Фонда (падение цен на нефть, пандемия COVID-19)
  2.2.3.1 Программы поддержки в кризисах
  2.2.3.1.1 Оценка успешности и влияние реализованных программ
  2.2.4 Роль МВФ при глобальных валютно-финансовых шоках и цифровой трансформации
  2.2.4.1 Примеры успешной адаптации к цифровым трансформациям
  2.2.4.2 Влияние на макроэкономическую политику стран – кредиторов/не заемщиков
  2.2.4.3 Интеграция цифровых активов в систему международных платежей
  2.2.5 Взаимоотношения с ключевыми игроками (США, ЕС и развивающиеся страны)
  2.2.5.1 Геополитическая роль США при управлении фондом
  2.2.5.2 Роль развивающихся стран – примеров Россия, Китай
  3 Критический обзор деятельности Фонда
  3.1 Политические аспекты регулирования с рекомендациями Фонда
  3.1.1 Влияние на монетарную и налогово-бюджетные политики стран-реципиентов
  3.1.1.2 Долгосрочные последствия реформ
  3.1.1.3 Социальные и политические последствия макроэкономических программ МВФ
  3.1.1.4 Взаимодействие с национальными регуляторами
  3.1.2 Влияние на укрепление центральных банков и министерств финансов стран-членов
  3.2 Критика фонда в контексте суверенитета участников, демократизации управления и геополитического влияния
  3.2.1 Реформы квотирования: вызовы и перспективы улучшения представительства развивающихся стран
  3.2.2 Геополитическая роль США и ЕС при стратегическом управлении фондом 
  3.2.3 Влияние БРИКС, АСЕАН на развитие МВФ
  3.3 Взаимодействие с глобальными экономическими блоками в антикризисной поддержке
  3.3.1 Участие региональных группировок (БРИКС, ЕАЭС) в реформировании фонда
  3.3.2 Геополитическая роль санкций и их влияние на операции фонда
  3.4 Эволюция международных валютно-финансовых отношений
  3.4.1 Перспективы развития резервных активов: цифровые валюты, СДР и юань
  3.4.1.1 Интеграция цифровых инструментов в международные операции фонда
  3.4.1.2 Применение блокчейн технологии для управления активами Фонда
  3.5. Антикризисное управление при участии МВФ
  3.5.1 Валютные кредиты, стабилизационные программы и макроэкономические результаты кризисов
  3.5.1.1 Поддержка баланса международных платежей стран-членов
  3.5.1.2 Влияние антикризисных мер на валютный рынок постсоветских стран
  3.5.2 Скоординированные усилия с международными финансовыми организациями для устойчивого развития
  3.5.2.1 Программы сотрудничества со Всемирным Банком и региональными институтами при поддержке инфраструктуры
  3.5.2.2 Влияние антикризисных мер на международные торговые связи
  3.5.2.3 Роль МВФ в международных валютно-финансовых соглашениях
  3.5.3 Макроэкономическая эффективность антикризисного подхода в контексте развивающихся и развитых стран
  3.5.3.1 Оценка влияния программ по регионам
prompts:
  generate: |
    Напиши один раздел для обзорной статьи по теме:

    {title}

    Раздел находится в следующей структуре разделов статьи, от более общих к частным:

    {path}

    Название раздела в этой структуре:

    {paragraph}

    Раздел может использовать информацию из приведённых ниже отрывков исходных статей:

    {sources}

    Нужно использовать информацию из приведённых выше отрывков исходных статей, но повторять предложения или фразы нельзя.

    Раздел находится в следующей структуре разделов обзорной статьи, от более общих к частным:

    {path}

    Название раздела в этой структуре:

    {paragraph}

    Напиши текст раздела - не менее 100 и не более 300 слов.

    Для каждого факта или мнения проставь в квадратных скобках номер источника, из которого получена эта информация.

    Ссылаться можно только на источники, указанные в запросе. На один источник нужно указывать только одну ссылку в тексте.

    В конце текста приведи нумерованный список наименований источников, указанных выше в запросе, на которые ты ставишь ссылки в тексте.

