script: embed.py
title: Роль международного валютного фонда в регулировании международных валютно-финансовых отношений
plan: |
  2 Теоретическая часть
    2.1 Регулирование международных валютно-финансовых отношений
      2.1.1 Основы функционирования и цели стабилизации финансовых рынков
      2.1.2 Механизмы регулирования международных валютно-финансовых отношений
    2.2 Международный Валютный Фонд
      2.2.1 История и принципы формирования МВФ
        2.2.1.1 Роль МВФ в послевоенном восстановлении
        2.2.1.2 От Бреттон-Вудcа к Ямайской системе и до наших дней
        2.2.1.3 Монетарные реформы в ответ на глобальные экономические кризисы
      2.2.2 Структура и управление МВФ
        2.2.2.1 Страны-участники
        2.2.2.2 Органы управления
        2.2.2.3 Международные комитеты
      2.2.3 Основные функции МВФ
        2.2.3.1 Экономический надзор и мониторинг мировой экономики
        2.2.3.2 Предоставление консультаций и аналитических исследований
        2.2.3.3 Кредитование стран-участниц
        2.2.3.4 Техническая помощь и обучение специалистов
      2.2.4 Сотрудничество с международными организациями
        2.2.4.1 Взаимодействие МВФ с Всемирным банком
        2.2.4.2 Взаимодействие МВФ с ВТО
        2.2.4.3 Взаимодействие МВФ с ООН
        2.2.4.4 Взаимодействие МВФ с Группой двадцати (G-20)
        2.2.4.5 Взаимодействие МВФ с БРИКС
      2.2.5 Проблемы реформирования МВФ
  3 Анализ источников
    3.1 Кредитование стран МВФ
      3.1.1 Виды кредитов Фонда и условия их предоставления
      3.1.2 Программы поддержки в кризисных ситуациях
    3.2 Монетарная политика Фонда
      3.2.1 Влияние на валютные курсы и инфляцию стран-реципиентов
      3.2.3 Расширение кредитных программ для долгосрочного развития экономик
    3.3 Критика МВФ: экономический и социальный аспекты деятельности фонда
        3.3.1 Опыт постсоветских государств (Россия, Украина)
        3.3.2 Опыт стран Европы (Греция, Ирландия)
        3.3.3 Опыт стран Азии (Индонезия, Малайзия)
    3.4 Политические аспекты МВФ
      3.4.1 Влияние США на управление Фондом
      3.4.2 Роль квот и голосования в принятии решений
      3.4.3 Конфликты интересов между странами G7 и развивающимися странами
    3.5 Перспективы развития международных валютно-финансовых отношений
      3.5.1 Мировые валюные системы и их реформирование
        3.5.1.1 Концепции многовалютного стандарта
        3.5.1.2 Наднациональная валюта: идеи и критика
          3.5.1.2.1 Возможности введения наднциональной валюты
          3.5.1.2.2 Сопротивление со стороны развитых стран
        3.5.1.3 Роль золота в современной валютной системе
        3.5.1.4 Интернационализация российского рубля
          3.5.1.4.1 Состояние на данный момент
          3.5.1.4.2 Пути укрепления статуса
        3.5.1.5 Интернационализация китайского юаня и других валют стран БРИКС
      3.5.2 Современные вызовы и кризисы в международной валютной системе
        3.5.2.1 Влияние цифровых валют на традиционные валютные системы
        3.5.2.2 Перспективы регулирования глобальных экономических кризисов
prompts:
  embed:
    model: deepseek-r1:32b
    options:
      num_ctx: 23107
  generate:
    model: deepseek-r1:32b
    options:
      num_ctx: 23107
    # model: infidelis/GigaChat-20B-A3B-instruct:q4_0
    # options:
    #   num_ctx: 131072
    template: |
      Напиши один раздел для обзорной статьи по теме:

      {title}

      Раздел находится в следующей структуре разделов статьи:

      {plan}

      Название раздела, который нужно написать, в этой структуре:

      {paragraph}

      Раздел может использовать информацию из приведённых ниже отрывков исходных статей:

      {sources}

      Нужно использовать информацию из приведённых выше отрывков исходных статей, но повторять предложения или фразы нельзя.

      Раздел находится в следующей структуре разделов обзорной статьи, от более общих к частным:

      {plan}

      Название раздела в этой структуре:

      {paragraph}

      Напиши текст раздела - не менее 100 и не более 300 слов и только на русском языке, не допускай китайского или английского.
      
      Не повторяй заголовок раздела и вообще не добавляй заголовков.

      Не приводи общие определения и вводные слова, если название раздела явно этого не подразумевает.
      
      Считай, что вводные слова содержатся в разделах верхнего уровня по структуре разделов статьи.

      Старайся детально и с указанием фактов раскрыть тему названного раздела, не переходя к другим темам и не погружаясь в них.

      Если у названного раздела есть подразделы, не погружайся в детали подразделов, укажи только то, что не названо в подразделах.

      Для каждого факта или мнения в тексте проставь в квадратных скобках только номер источника, из которого получена эта информация.

      Ссылаться можно только на источники, указанные в запросе, используя их номера, не указывая фамилию и год.
      
      Во всём тексте твоего ответа на один источник нужно указывать ссылку только в одном месте, которое лучше всего подходит.
  rewrite:
    # model: infidelis/GigaChat-20B-A3B-instruct:q4_0
    # options:
    #   num_ctx: 131072
    model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
    options:
      num_ctx: 32768
    token_factor: 5
    template: |
    
      Перепиши приведённый ниже текст, сохранив его примерный объём.

      Замени в нём все китайские слова на русские аналоги. Сделай текст более связным, сохранив смысл.

      Удали дубли по смыслу между разделами, каждый факт или мнение приведи в тексте только один раз.

      Обязательно сохрани номера ссылок из списка литературы в квадратных скобках в каждом разделе текста.

      Заполни разделы Введение и Заключение в соответствии со смыслом всего текста. Название в первой строке не меняй.

      Разделы Введение и Заключение должны содержать не менее 500 слов, все остальные разделы - не менее 300.

      Используй в каждом разделе те же самые сслыки (номера в квадратных скобках), которые даны в исходном тексте.

      # {title}

      ## 1. Введение

      {source}

      ## 4. Заключение

      ## Список литературы

      {citations}

      Перепиши приведённый выше текст, сохранив структуру заголовков и объём текста в каждом из разделов.

      Замени в нём все китайские слова на русские аналоги. Сделай текст более связным, сохранив смысл.

      Удали дубли по смыслу между разделами, каждый факт или мнение приведи в тексте только один раз.

      Обязательно сохрани номера ссылок из списка литературы в квадратных скобках в каждом разделе текста.

      Заполни разделы Введение и Заключение в соответствии со смыслом всего текста. Название в первой строке не меняй.

      Разделы Введение и Заключение должны содержать не менее 500 слов, все остальные разделы - не менее 300.

      Используй в каждом разделе те же самые сслыки (номера в квадратных скобках), которые даны в исходном тексте.
  rewrite_paragraph:
    # model: infidelis/GigaChat-20B-A3B-instruct:q4_0
    # options:
    #   num_ctx: 131072
    model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
    options:
      num_ctx: 32768
    token_factor: 5
    template: |

      Перед тобой следующий черновик обзорной статьи, уже отредактированный от начала и до целевого раздела.

      {source}
    
      Перепиши текст приведённого ниже раздела, сохранив структуру заголовков и объём текста в каждом из разделов.

      Замени в нём все китайские слова на русские аналоги. Сделай текст более связным, сохранив смысл.

      Удали дубли по смыслу между разделами, каждый факт или мнение приведи в тексте только один раз.

      Обязательно сохрани номера ссылок из списка литературы в квадратных скобках в каждом разделе текста.

      Заполни разделы Введение и Заключение в соответствии со смыслом всего текста. Название в первой строке не меняй.

      Разделы Введение и Заключение должны содержать не менее 500 слов, все остальные разделы - не менее 300.

      Используй в каждом разделе те же самые сслыки (номера в квадратных скобках), которые даны в исходном тексте.

      Перепиши текст только одного приведённого ниже раздела, не включая в ответ какие-либо другие разделы.

      {paragraph}
  write_paragraph:
    # model: infidelis/GigaChat-20B-A3B-instruct:q4_0
    # options:
    #   num_ctx: 131072
    model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
    options:
      num_ctx: 32768
    template: |

      Перед тобой следующий черновик обзорной статьи.

      {source}
    
      Напиши раздел {title} - не менее 500 слов.
      
      Сделай текст связным в соответствии со смыслом всего текста.
