script: embeddings.py
# model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
# model: infidelis/GigaChat-20B-A3B-instruct:q4_0
# model: evilfreelancer/o1_gigachat:20b-q4_0
model: deepseek-r1:14b
num_ctx: 22768
window_size: 1
title: Роль международного валютного фонда в регулировании международных валютно-финансовых отношений
plan: |
  2. Теоретическая часть
    2.1. Регулирование международных валютно-финансовых отношений
    2.2. Международный валютофонд
      2.2.1. История и основные принципы МВФ
      2.2.2. Основные функции МВФ
        2.2.2.1. Предоставление консультаций и аналитических исследований
        2.2.2.2. Кредитование стран-участниц
        2.2.2.3. Техническая помощь и обучение
      2.2.3. Сотрудничество с международными организациями
        2.2.3.1. Взаимодействие с Всемирным банком
        2.2.3.2. Взаимодействие с ВТО
        2.2.3.3. Взаимодействие с ООН
        2.2.3.4. Взаимодействие с Группой двадцати (G-20)
      2.2.4. Проблемы реформирования МВФ
  3. Анализ источников
    3.1. Политические аспекты МВФ
      3.1.1. Влияние США на управление Фонда
      3.1.2. Роль квот и голосования в принятии решений
      3.1.3. Конфликты интересов между странами G7 и развивающимися странами
    3.2. Перспективы развития международных валютно-финансовых отношений
      3.2.3. Мировые валюные системы и их реформирование
        3.2.3.1. Концепции многовалютного стандарта
        3.2.3.2. Супранациональная валюта: идеи и критика
          3.2.2.2.1. Возможности введения супранциональной валюты
          3.2.2.2.2. Сопротивление со стороны развитых стран
        3.2.3.3. Роль золота в современной валюной системе
        3.2.3.4. Интернационализация российского рубля
          3.2.3.4.1. Состояние на данный момент
          3.2.3.4.2. Пути укрепления статуса
        3.2.3.5. Интернационализация китайского юаня и других валют стран BRICS
      3.2.4. Современные вызовы и кризисы в международной валюной системе
        3.2.4.1. Влияние цифровых валют на традиционные валютные системы
        3.2.4.2. Регулирование глобальных экономических кризисов через МВФ
prompts:
  generate: |
    Напиши один раздел для обзорной статьи по теме:

    {title}

    Раздел находится в следующей структуре разделов статьи:

    {plan}

    Название раздела, который нужно написать, в этой структуре:

    {paragraph}

    Раздел может использовать информацию из приведённых ниже отрывков исходных статей:

    {sources}

    Нужно использовать информацию из приведённых выше отрывков исходных статей, но повторять предложения или фразы нельзя.

    Раздел находится в следующей структуре разделов обзорной статьи, от более общих к частным:

    {plan}

    Название раздела в этой структуре:

    {paragraph}

    Напиши текст раздела - не менее 100 и не более 300 слов. Не повторяй заголовок раздела и вообще не добавляй заголовков.

    Для каждого факта или мнения в тексте проставь в квадратных скобках только номер источника, из которого получена эта информация.

    Ссылаться можно только на источники, указанные в запросе, используя их номера, не указывая фамилию и год.
    
    Во всём тексте твоего ответа на один источник нужно указывать ссылку только в одном месте, которое лучше всего подходит.

