script: generate.py
index: data/cryptosarf/crypto-snow.faiss
title: Криптовалюта как исламский финансовый инструмент
plan: |
  1. Введение
  2. Теоретическая часть  
    2.1. Источники шариата, принципы исламских финансов и их эволюция в цифровую эпоху  
      2.1.1. Запрет риба (riba) и спекулятивных сделок  
      2.1.2. Участие в реальных экономических процессах (мурабаха, мудараба, сукук)  
      2.1.3. Требование прозрачности и справедливости в сделках  
      2.1.4. Стандарты обеспечения активами (например, AAOIFI)  
      2.1.5. Роль консенсуса улемов ("мувафакат") в принятии инновационных финансовых инструментов  
    2.2. Криптовалюты как цифровые активы: соответствие принципам шариата  
      2.2.1. Отсутствие процентных механизмов (riba)  
      2.2.2. Риск-менеджмент и концепция «гарар» в контексте криптовалютной волатильности  
      2.2.3. Соответствие принципам реального эквивалента (например, обеспечение золотом как в случае OneGram)  
      2.2.4. Критерий «меры стоимости» и независимость от фиатных валют  
    2.3. Технологические основы блокчейн: децентрализация, безопасность и их этическая оценка в шариате  
      2.3.1. Прозрачность реестров vs. анонимность транзакций  
      2.3.2. Возможности для манипуляций и соответствие принципам справедливости  
      2.3.3. Использование смарт-контрактов для автоматизации шариатских условий в сделках
      2.3.4. Платформы самообслуживания и цифровизация клиентских процессов
    2.4. Исторический контекст альтернативных валют (золотой динар, e-Dinar) как предшественников цифровых решений в исламской экономике  
  3. Обзор практики применения криптовалют в соответствии с нормами шариата  
    3.1. Фетвы исламских учёных по криптовалютам: спектр мнений от запрета до условного разрешения  
    3.2. Практические кейсы в исламском мире
      3.2.1. Использование e-Dinar, OneGram, IslamicCoin
      3.2.2. Пилотные блокчейн-платформы: проекты Дубайского департамента экономического развития, система мгновенных платежей «Сари» (Саудовская Аравия)  
      3.2.3. Использование стейблкоинов в микрофинансировании и халяль-секторе 
      3.2.4. Кейс HelloGold (Малайзия): золото-поддержанные токены с шариат-комплиантным управлением  
      3.2.5. Развитие P2P-платформ в Индонезии: Amartha, Investree, Alami Sharia  
      3.2.6. Криптобиржи в ОАЭ (BitOasis) и Саудовской Аравии с шариат-фильтрами  
      3.2.7. Примеры цифровизации клиентских сервисов в казахстанском банке «Al Hilal»: платформы самообслуживания, роботы-советники  
      3.2.8. Платформа Bursa Suq Al Sila (Малайзия) для торговли сырьевыми товарами в соответствии с шариатом  
      3.2.9. Финтех-альянс IFT Alliance и его роль в глобализации исламских финтех-решений 
    3.3. Регуляторная политика мусульманских стран
      3.3.1 Запреты или эксперименты: Саудовская Аравия (проект Aber, регулятивные песочницы), ОАЭ (VARA, закон «О виртуальных активах»)  
      3.3.2 Регулирование на Мальдивах: лицензионные требования для шариат-комплиантных крипто-платформ  
      3.3.3 Адаптация международных стандартов (Basel III) через национальные комитеты (например, ОАЭ: CBDC-стратегия до 2036 г.)  
      3.3.4 Регуляторные песочницы в Саудовской Аравии и Катаре для тестирования шариат-комплиантных крипто-инноваций  
      3.3.5 Внедрение нормативных актов противодействия отмыванию средств (ACX, VARA)  
    3.4. Роль международных институтов (Исламский банк развития, AAOIFI) в стандартизации использования криптовалют
    3.5. Геоэкономическая роль криптовалют: снижение зависимости от долларовой системы и усиление интеграции мусульманских стран в международные финансовые потоки  
    3.6. Социальные преимущества использования криптовалют
      3.6.1. Снижение инфляционного давления через децентрализованную эмиссию
      3.6.2. Этическое распределение благ: противодействие уклонению от налогов и мошенничеству
      3.6.3. Использование стейблкоинов для халяль-кредитования  
      3.6.4. Социальное расслоение из-за неравномерного владения криптовалютами
      3.6.5. Роль мобильных приложений в расширении доступности финтех-услуг
    3.7. Риски и вызовы
      3.7.1. Анонимность транзакций vs. требования прозрачности шариата (конфликт с принципами «аль-маля»)  
      3.7.3. Манипулирование рынком криптовалют
      3.7.4. Угрозы финансирования терроризма    
      3.7.5. Экологические проблемы: энергопотребление майнинга
      3.7.6. Зависимость от интернет-инфраструктуры (масштабируемость)  
      3.7.7. Низкая финансовая грамотность населения и кадровые ограничения в разработке шариат-комплиантных решений  
      3.7.8. Конкуренция с традиционными инструментами
    3.8. Перспективы криптовалют для халяль-финансирования
      3.8.1. Цифровые сукук, P2P-инвестиции
      3.8.2. Управление активами через смарт-контракты
      3.8.3. Токенизация земельных участков, сельхозпроизводства, халяль-глобальных цепочек поставок  
      3.8.4. Развитие Metaverse финансов (MetaFi): интеграция DeFi/CeFi/TradFi с шариатскими стандартами  
      3.8.5. Внедрение краудфандинга и роботов-советников для расширения доступности услуг  
      3.8.6. Интеграция Insurtech в страховые продукты, соответствующие шариату 
      3.8.7. Концепция «Исламский стейблкоин» с золотом и халяль-активами в качестве обеспечения
      3.8.8. Создание CBDC в соответствии с шариатом и их интеграция с криптовалютами  
  4. Заключение
# 1. Введение
# 2. Теоретическая часть  
#   2.1 Источники шариата, принципы исламских финансов и их эволюция в цифровую эпоху  
#   2.2 Криптовалюта с точки зрения исламского права: анализ запретов (риба, гарар) и возможных аналогий с традиционными инструментами  
#   2.3 Технологические особенности криптовалют в свете шариата: блокчейн, децентрализация, смарт-контракты  
#   2.4 Исторический контекст альтернативных валют (золотой динар, e-Dinar) как предшественников цифровых решений в исламской экономике  
# 3. Обзор практики применения криптовалют в соответствии с нормами шариата  
#   3.1 Фетвы исламских учёных по криптовалютам: спектр мнений от запрета до условного разрешения  
#   3.2 Практические кейсы в исламском мире: использование e-Dinar, OneGram, IslamicCoin
#   3.3 Регуляторная политика мусульманских стран: законодательные запреты, лицензирование, создание регулятивных песочниц и CBDC
#   3.4 Роль международных институтов (Исламский банк развития, AAOIFI) в стандартизации использования криптовалют
#   3.5 Геоэкономическая роль криптовалют: снижение зависимости от долларовой системы и усиление интеграции мусульманских стран в международные финансовые потоки  
#   3.6 Социальные преимущества использования криптовалют: доступность для маргинальных групп, противодействие инфляции, инвестиции в халяль-сектор  
#   3.7 Этические риски: манипулирование рынком криптовалют и угроза финансирования терроризма через анонимность транзакций  
#   3.8 Критические вызовы: технологическая незрелость (масштабируемость, энергопотребление, стандарты безопасности), конкуренция с традиционными инструментами
#   3.9 Перспективы криптовалют для халяль-финансирования: цифровые сукук, P2P-инвестиции, управление активами через смарт-контракты
# 4. Заключение
prompts:
  embed:
    window_size: 0
    max_samples: 20
    model: snowflake-arctic-embed2:latest
    max_tokens: 8192
  generate:
    model: deepseek-r1:32b
    max_tokens: 32768
    template: |
      Напиши один раздел для обзорной статьи по теме:

      {title}

      Раздел, который нужно написать - первый не заполненный в следующей структуре статьи (до маркера <<ИНСТРУКЦИИ>>):

      {draft}

      <<ИНСТРУКЦИИ>>

      Название раздела, который нужно написать, в этой структуре:

      {paragraph}

      Раздел может использовать информацию из приведённых ниже отрывков исходных статей (до маркера <<ИНСТРУКЦИИ>>):

      {sources}

      <<ИНСТРУКЦИИ>>

      Нужно использовать информацию из приведённых выше отрывков исходных статей, но повторять предложения или фразы нельзя.

      Раздел находится в следующей структуре разделов обзорной статьи, от более общих к частным:

      {plan}

      Название раздела в этой структуре:

      {paragraph}

      Напиши текст раздела - не менее 500 и не более 1000 слов и только на русском языке, не допускай китайского или английского.
      
      Не повторяй заголовок раздела и вообще не добавляй заголовков.

      Старайся детально и с указанием фактов раскрыть тему названного раздела, не переходя к другим темам и не погружаясь в них.

      Для каждого факта или мнения в тексте проставь в квадратных скобках только номер источника, из которого получена эта информация.

      Ссылаться можно только на те источники, которые указаны в запросе, используя их номера, не указывая фамилию и год.
      
      Во всём тексте твоего ответа на один источник нужно указывать ссылку только в одном месте, которое лучше всего подходит.

      Напиши текст раздела - не менее 500 и не более 1000 слов и только на русском языке, не допускай китайского или английского.
      