script: generate.py
index: data/cryptosarf/crypto-snow.faiss
title: Криптовалюта как исламский финансовый инструмент
plan: |
  1. Введение
  2. Теоретическая часть  
    2.1 Источники шариата, принципы исламских финансов и их эволюция в цифровую эпоху  
    2.2 Криптовалюта с точки зрения исламского права: анализ запретов (риба, гарар) и возможных аналогий с традиционными инструментами  
    2.3 Технологические особенности криптовалют в свете шариата: блокчейн, децентрализация, смарт-контракты  
    2.4 Исторический контекст альтернативных валют (золотой динар, e-Dinar) как предшественников цифровых решений в исламской экономике  
  3. Обзор практики применения криптовалют в соответствии с нормами шариата  
    3.1 Фетвы исламских учёных по криптовалютам: спектр мнений от запрета до условного разрешения  
    3.2 Практические кейсы в исламском мире: использование e-Dinar, OneGram, IslamicCoin
    3.3 Регуляторная политика мусульманских стран: законодательные запреты, лицензирование, создание регулятивных песочниц и CBDC
    3.4 Роль международных институтов (Исламский банк развития, AAOIFI) в стандартизации использования криптовалют
    3.5 Геоэкономическая роль криптовалют: снижение зависимости от долларовой системы и усиление интеграции мусульманских стран в международные финансовые потоки  
    3.6 Социальные преимущества использования криптовалют: доступность для маргинальных групп, противодействие инфляции, инвестиции в халяль-сектор  
    3.7 Этические риски: манипулирование рынком криптовалют и угроза финансирования терроризма через анонимность транзакций  
    3.8 Критические вызовы: технологическая незрелость (масштабируемость, энергопотребление, стандарты безопасности), конкуренция с традиционными инструментами
    3.9 Перспективы криптовалют для халяль-финансирования: цифровые сукук, P2P-инвестиции, управление активами через смарт-контракты
  4. Заключение
prompts:
  embed:
    window_size: 0
    max_samples: 20
    model: snowflake-arctic-embed2:latest
    options:
      num_ctx: 8192
  generate:
    model: deepseek-r1:32b
    options:
      num_ctx: 43690
    template: |
      Напиши один раздел для обзорной статьи по теме:

      {title}

      Раздел, который нужно написать - первый не заполненный в следующей структуре статьи (до маркера <<ИНСТРУКЦИИ>>):

      {draft}

      <<ИНСТРУКЦИИ>>

      Название раздела, который нужно написать, в этой структуре:

      {paragraph}

      Раздел может использовать информацию из приведённых ниже отрывков исходных статей (до маркера <<ИНСТРУКЦИИ>>):

      {sources}

      <<ИНСТРУКЦИИ>>

      Нужно использовать информацию из приведённых выше отрывков исходных статей, но повторять предложения или фразы нельзя.

      Раздел находится в следующей структуре разделов обзорной статьи, от более общих к частным:

      {plan}

      Название раздела в этой структуре:

      {paragraph}

      Напиши текст раздела - не менее 500 и не более 1000 слов и только на русском языке, не допускай китайского или английского.
      
      Не повторяй заголовок раздела и вообще не добавляй заголовков.

      Старайся детально и с указанием фактов раскрыть тему названного раздела, не переходя к другим темам и не погружаясь в них.

      Для каждого факта или мнения в тексте проставь в квадратных скобках только номер источника, из которого получена эта информация.

      Ссылаться можно только на те источники, которые указаны в запросе, используя их номера, не указывая фамилию и год.
      
      Во всём тексте твоего ответа на один источник нужно указывать ссылку только в одном месте, которое лучше всего подходит.

      Напиши текст раздела - не менее 500 и не более 1000 слов и только на русском языке, не допускай китайского или английского.
      