script: generate.py
index: data/cryptosarf/crypto-snow.faiss
title: Криптовалюта как исламский финансовый инструмент
plan: |
  2 Теоретическая часть  
    2.1 Исламские принципы финансов: запрет риба, гарар, майсири и нормативные основы шариата  
    2.2 Эволюция финансовых инструментов в цифровой эпохе: от золотого динара к блокчейн-технологиям  
    2.3 Криптовалюты через призму исламского права: разрешенность, этические ограничения и юридические вызовы  
    2.4 Технологическая инфраструктура криптовалют (блокчейн, смарт-контракты) в свете шариатских требований  
  3 Практические аспекты применения криптовалют в исламской финансовой системе  
    3.1 Фетвы исламских учёных: споры о халяльности цифровых денег, примеры запретов и разрешений (на примере e-Dinar и OneGram)  
    3.2 Кейсы внедрения криптовалют в мусульманском мире: проекты на блокчейне (например, российский цифровой сукук)  
    3.3 Регуляторная политика мусульманских стран: законодательные запреты, лицензирование и создание регулятивных песочниц  
    3.4 Социальные последствия: инвестиции в халяль-сектор, противодействие инфляции через децентрализованные активы  
    3.5 Этические риски: манипулирование рынком криптовалют и угроза финансирования терроризма через анонимность транзакций  
  4 Геополитический контекст и глобальная роль криптовалют  
    4.1 Криптовалюты как инструмент децентрализации: альтернатива долларовоцентристской системе в рамках БРИКС+ и ЕАЭС  
    4.2 Конкуренция с национальными цифровыми валютами (e-CNY, цифровой евро) в мусульманских государствах: примеры ОАЭ и Саудовской Аравии  
  5 Перспективы развития исламских финтех-проектов  
    5.1 Возможности блокчейна для халяль-финансирования: цифровые сукук, P2P-инвестиции, управление активами через смарт-контракты  
    5.2 Конфликт интересов между децентрализацией криптовалют и регулируемыми шариатскими институтами (на примере России и Малайзии)
# 2 Теоретическая часть  
#   2.1 Принципы исламских финансов и их эволюция в цифровую эпоху  
#     2.1.1 Источники шариата в экономической сфере: Коран, Сунна и фикховые интерпретации  
#     2.1.2 Запреты риба (ростовщичество) и гарара (ненужного риска) как основа исламских финансов  
#     2.1.3 Трансформация денежных инструментов в цифровую эпоху: от золотого динара к криптовалютам  
#   2.2 Криптовалюта с точки зрения исламского права  
#     2.2.1 Обсуждение статуса криптовалют как фиата, товара или цифрового актива в свете шариата  
#     2.2.2 Анализ запретов спекулятивных операций (майсир) и их связи с торговлей криптой  
#     2.2.3 Разрешенные формы использования: обеспечение золотом/серебром, долевые инвестирования по модели мудараба  
#   2.3 Технологические особенности криптовалют в свете шариата  
#     2.3.1 Блокчейн как средство обеспечения прозрачности и отслеживания сделок  
#     2.3.2 Риски децентрализации: контроль над эмиссией, непредсказуемость курса и соответствие принципам шариата  
#     2.3.3 Альтернативные модели: криптозолото (например, OneGram) vs. спекулятивные активы  
# 3 Обзор практики применения криптовалют в соответствии с нормами шариата  
#   3.1 Фетвы исламских учёных по криптовалютам  
#     3.1.1 Консервативный подход: запреты из-за неопределённости статуса актива (мудтахала)  
#     3.1.2 Прогрессивные интерпретации: разрешение при соблюдении принципов партнёрства и реального обеспечения  
#     3.1.3 Региональные различия в фикховых мнениях (например, ОАЭ vs. Саудовская Аравия)  
#   3.2 Практические кейсы в исламском мире  
#     3.2.1 Электронная система E-Dinar: пример интеграции золотого стандарта с цифровыми технологиями  
#     3.2.2 Использование стейблкоинов, обеспеченных драгметаллами в ОАЭ и Турции  
#     3.2.3 Попытки создания «чисто-шариатских» блокчейн-платформ (например, ShariahCoin)  
#   3.3 Регуляторная политика мусульманских стран  
#     3.3.1 Запреты и ограничения: примеры Малайзии, Ирана, Саудовской Аравии  
#     3.3.2 Пилотные проекты: цифровые валюты Центробанков (CBDC) в свете шариата  
#     3.3.3 Роль международных институтов (Исламский банк развития, AAOIFI) в стандартизации  
#   3.4 Социальные преимущества использования криптовалют  
#     3.4.1 Диверсификация резервов мусульманских стран за счёт выхода из долларовой зависимости  
#     3.4.2 Снижение транзакционных издержек для мигрантов и международной торговли в исламском мире  
#     3.4.3 Поддержка микрофинансирования и доступности финансовых услуг в регионах с ослабленными банками  
#   3.5 Геоэкономическая роль криптовалют  
#     3.5.1 Контрпротиводействие гегемонии западных фиатов через создание альтернативных финансовых коридоров  
#     3.5.2 Влияние на торговлю энергоресурсами: примеры Саудовской Аравии и Ирана в экспериментах с криптой  
#     3.5.3 Риски дезинтеграции экономик из-за противоречий в регуляторных подходах внутри ОИК  
#   3.6 Перспективы развития и критические вызовы  
#     3.6.1 Технические барьеры: масштабируемость, энергопотребление, стандарты безопасности  
#     3.6.2 Социально-религиозные конфликты: позиция улемов vs. интересы финансовых рынков  
#     3.6.3 Геополитическая борьба за контроль над новыми финансовыми инструментами между исламскими державами и Западом
prompts:
  embed:
    window_size: 0
    max_samples: 20
    model: snowflake-arctic-embed2:latest
    # model: bge-m3:latest
    options:
      num_ctx: 8192
      # num_ctx: 131072
  generate:
    # model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
    model: deepseek-r1:32b
    options:
      # num_ctx: 32768
      num_ctx: 43690
    template: |
      Напиши один раздел для обзорной статьи по теме:

      {title}

      Раздел, который нужно написать - первый не заполненный в следующей структуре статьи (до маркера <<ИНСТРУКЦИИ>>):

      {draft}

      <<ИНСТРУКЦИИ>>

      Название раздела, который нужно написать, в этой структуре:

      {paragraph}

      Раздел может использовать информацию из приведённых ниже отрывков исходных статей (до маркера <<ИНСТРУКЦИИ>>):

      {sources}

      <<ИНСТРУКЦИИ>>

      Нужно использовать информацию из приведённых выше отрывков исходных статей, но повторять предложения или фразы нельзя.

      Раздел находится в следующей структуре разделов обзорной статьи, от более общих к частным:

      {plan}

      Название раздела в этой структуре:

      {paragraph}

      Напиши текст раздела - не менее 500 и не более 1000 слов и только на русском языке, не допускай китайского или английского.
      
      Не повторяй заголовок раздела и вообще не добавляй заголовков.

      Не приводи общие определения и вводные слова, если название раздела явно этого не подразумевает.
      
      Считай, что вводные слова содержатся в разделах верхнего уровня по структуре разделов статьи.

      Старайся детально и с указанием фактов раскрыть тему названного раздела, не переходя к другим темам и не погружаясь в них.

      Если у названного раздела есть подразделы, не погружайся в детали подразделов, укажи только то, что не названо в подразделах.

      Для каждого факта или мнения в тексте проставь в квадратных скобках только номер источника, из которого получена эта информация.

      Ссылаться можно только на источники, указанные в запросе, используя их номера, не указывая фамилию и год.
      
      Во всём тексте твоего ответа на один источник нужно указывать ссылку только в одном месте, которое лучше всего подходит.
