script: phrases.py
prompts:
  rephrase:
    # model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
    # options:
    #   num_ctx: 32768
    model: infidelis/GigaChat-20B-A3B-instruct:q4_0
    options:
      num_ctx: 131072
    template: |
      Напиши новый вариант текста по примерам, указанным ниже.

      {source}

      Постарайся передать смысл текста как можно точнее.
      Не должно быть совпадений с приведённым выше текстом даже в отдельных фразах!
      Главное: текст должен быть содержать не менее {words} слов.
