script: rephrase.py
model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
num_ctx: 22768
prompts:
  rephrase: |
    Напиши третий вариант текста по примерам, указанным ниже.
    Первый вариант:

    {request}

    Второй вариант:

    {response}

    Постарайся передать смысл текста как можно точнее.
    Не должно быть совпадений с первым и вторым вариантами даже в отдельных фразах!
    Главное: текст должен быть содержать не менее {words} слов.
