script: phrases.py
prompts:
  rephrase:
    model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
    options:
      num_ctx: 32768
    template: |
      Напиши третий вариант текста по примерам, указанным ниже.
      Первый вариант:

      {request}

      Второй вариант:

      {response}

      Постарайся передать смысл текста как можно точнее.
      Не должно быть совпадений с первым и вторым вариантами даже в отдельных фразах!
      Главное: текст должен быть содержать не менее {words} слов.
