script: plan.py
title: Криптовалюта как исламский финансовый инструмент
onebyone: False
plan: |
  1. Введение
  2. Теоретическая часть
    2.1 Принципы исламских финансов и их эволюция в цифровую эпоху
    2.1 Криптовалюта с точки зрения исламского права
    2.2 Технологические особенности криптовалют в свете шариата
  3. Обзор практики применения криптовалют в соответствии с нормами шариата
    3.1 Фетвы исламских учёных по криптовалютам
    3.2 Практические кейсы в исламском мире
    3.3 Регуляторная политика мусульманских стран
    3.5 Социальные преимущества использования криптовалют
    3.4 Геоэкономическая роль криптовалют
    3.6 Перспективы развития и критические вызовы
  4. Заключение
prompts:
  summary:
    model: infidelis/GigaChat-20B-A3B-instruct:q4_0
    options:
      num_ctx: 131072
    template: |
      Напиши на русском языке от {min} до {max} слов краткого содержания смысла приведённого ниже раздела из научной статьи:

      {source}

      Напиши на русском языке от {min} до {max} слов краткого содержания смысла приведённого выше раздела из научной статьи.
  plan:
    model: qwq:latest
    options:
      num_ctx: 43690
    template: |
      Насколько считаешь нужным, дополни и скорректируй план обзорной статьи по теме:

      {title}

      Вот план, собранный по предыдущим источникам:

      {plan}

      Ты можешь менять пункты только второго и более глубоких уровней вложенности, а также добавлять новые пункты и уровни вложенности списка.

      Вот тексты исходных статей, на основании которого нужно обновить план обзорной статьи:

      {source}

      На основании приведённых выше текстов, насколько считаешь нужным, дополни и скорректируй этот план обзорной статьи:

      {plan}

      Выводи только пункты плана, каждый с новой строки! C нумерацией, без пояснений и объяснений, и только на русском языке.

