script: plan.py
title: Роль международного валютного фонда в регулировании международных валютно-финансовых отношений
plan: |
  1. Введение
  2. Теоретическая часть
    2.1. Регулирование международных валютно-финансовых отношений
    2.2. Международный валютный фонд
  3. Анализ источников
    3.1. Политические аспекты международного валютный фонда
    3.2. Перспективы развития международных валютно-финансовых отношений
  4. Заключение
prompts:
  summary:
    model: infidelis/GigaChat-20B-A3B-instruct:q4_0
    options:
      num_ctx: 131072
    template: |
      Напиши на русском языке от {min} до {max} слов краткого содержания смысла приведённого ниже раздела из научной статьи:

      {source}

      Напиши на русском языке от {min} до {max} слов краткого содержания смысла приведённого выше раздела из научной статьи.
  plan:
    model: deepseek-r1:32b
    options:
      num_ctx: 131072
    template: |
      Насколько считаешь нужным, дополни и скорректируй план обзорной статьи по теме:

      {title}

      Вот план, собранный по предыдущим источникам:

      {plan}

      Ты можешь менять пункты второго уровня вложенности и ниже, а также добавлять новые.

      Вот текст одной из исходных статей, на основании которого нужно обновить план обзорной статьи:

      {source}

      На основании приведённого выше текста одного из источников, дополни и скорректируй этот план обзорной статьи:

      {plan}

      Выводи только пункты плана, каждый с новой строки! C нумерацией, без пояснений и объяснений, и только на русском языке.

