script: plan.py
onebyone: False
prompts:
  summary:
    model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
    max_tokens: 32768
    template: |
      Напиши на русском языке от {min} до {max} слов краткого содержания смысла приведённого ниже раздела из научной статьи:

      {source}

      Напиши на русском языке от {min} до {max} слов краткого содержания смысла приведённого выше раздела из научной статьи.
  plan:
    model: deepseek-r1:32b
    max_tokens: 32768
    template: |
      Насколько считаешь нужным, уточни, дополни и скорректируй план обзорной статьи по теме:

      {title}

      Вот план, собранный по предыдущим источникам:

      {plan}

      Ты можешь добавлять новые пункты и уровни вложенности списка, а также менять пункты только второго и более глубоких уровней вложенности.

      Старайся не пропустить никаких важных для плана моментов, приведённых в исходных статьях.
      
      Затем важные моменты должно быть возможно получить векторным поиском по тексту каждого из пунктов плана.

      Вот тексты исходных статей, на основании которого нужно обновить план обзорной статьи:

      {source}

      На основании приведённых выше текстов, насколько считаешь нужным, уточни, дополни и скорректируй этот план обзорной статьи:

      {plan}

      Выводи только план целиком, все его пункты, каждый с новой строки! C нумерацией, без пояснений и объяснений, и только на русском языке.

