script: plan.py
# model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
# model: infidelis/GigaChat-20B-A3B-instruct:q4_0
# model: evilfreelancer/o1_gigachat:20b-q4_0
model: deepseek-r1:14b
num_ctx: 22768
title: Роль международного валютного фонда в регулировании международных валютно-финансовых отношений
plan: |
  1. Введение
  2. Теоретическая часть
    2.1. Регулирование международных валютно-финансовых отношений
    2.2. Международный валютный фонд
  3. Анализ источников
    3.1. Политические аспекты международного валютный фонда
    3.2. Перспективы развития международных валютно-финансовых отношений
  4. Заключение
prompts:
  plan: |
    Насколько считаешь нужным, дополни и скорректируй план обзорной статьи по теме:

    {title}

    Вот план, собранный по предыдущим источникам:

    {plan}

    Ты можешь менять пункты второго уровня вложенности и ниже, а также добавлять новые.

    Вот текст одной из исходных статей, на основании которого нужно обновить план обзорной статьи:

    {source}

    На основании приведённого выше текста одного из источников, дополни и скорректируй этот план обзорной статьи:

    {plan}

    Выводи только пункты плана, каждый с новой строки, с нумерацией и без пояснений и объяснений и только на русском языке.

