script: summaries.py
model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
num_ctx: 22768
max_words: 500
prompts:
  section: |
    Напиши на русском языке от 100 до 150 слов краткого содержания смысла приведённого ниже раздела из научной статьи:

    {input}

    Напиши на русском языке от 100 до 150 слов краткого содержания смысла приведённого выше раздела из научной статьи.
    В конце перечисли через запятую ключевые слова или фразы для приведённого выше раздела из научной статьи, начиная с пометки "Ключевые слова: ".

  paper: |
    Укажи в ответе следующие свойства приведённой ниже статьи, строго соблюдая формат JSON:
    {{
    "title": "твой вариант названия статьи, который передаёт её смысл самым точным образом, не менее 7, не более 15 слов на русском языке, c заглавной буквы может начинаться только первое слово названия, имена собственные и аббревиатуры",
    "keywords": ["список ключевых слов", "или ключевых фраз", "для этой статьи", "потенциально повторяющихся в других статьях по этой теме", "в формате массива JSON", "не менее 5", "не более 10", "на русском языке"],
    "summary": "аннотация, которую ты предлагаешь для этой статьи, не менее 100, не более 150 слов на русском языке",
    }}

    Ниже {description}:

    {input}

    Выше {description}.

    Укажи в ответе следующие свойства приведённой выше статьи, строго соблюдая формат JSON:
    {{
    "title": "твой вариант названия статьи, который передаёт её смысл самым точным образом, не менее 7, не более 15 слов на русском языке, c заглавной буквы может начинаться только первое слово названия, имена собственные и аббревиатуры",
    "keywords": ["список ключевых слов", "или ключевых фраз", "для этой статьи", "потенциально повторяющихся в других статьях по этой теме", "в формате массива JSON", "не менее 5", "не более 10", "на русском языке"],
    "summary": "аннотация, которую ты предлагаешь для этой статьи, не менее 100, не более 150 слов на русском языке",
    }}

    Список ключевых слов из других статей для примера приведён ниже. Лучше выбирать ключевые слова из этого списка, но можешь предлагать новые в таком же ключе.

    {keywords}