script: summaries.py
model: rscr/ruadapt_qwen2.5_32b:Q4_K_M
num_ctx: 22768
max_blocks: 25
max_words: 3050
prompts:
  section: |
    Напиши на русском языке от 100 до 150 слов в качестве аннотации приведённого ниже раздела из научной статьи:

    {input}
  paper: |
    Укажи в ответе следующие свойства приведённой ниже статьи, строго соблюдая формат JSON:
    {{
    "title": "твой вариант названия статьи, который передаёт её смысл самым точным образом, не менее 7, не более 15 слов на русском языке, заглавными только первое слово, имена собственные и аббревиатуры",
    "keywords": ["список ключевых слов", "или ключевых фраз", "для этой статьи", "потенциально повторяющихся в других статьях по этой теме", "в формате массива JSON", "не менее 5", "не более 10", "на русском языке"],
    "summary": "аннотация, которую ты предлагаешь для этой статьи, не менее 100, не более 150 слов на русском языке",
    }}

    Ниже {description}:

    {input}

    Выше {description}.

    Укажи в ответе следующие свойства приведённой выше статьи, строго соблюдая формат JSON:
    {{
    "title": "твой вариант названия статьи, который передаёт её смысл самым точным образом, не менее 7, не более 15 слов на русском языке, заглавными только первое слово, имена собственные и аббревиатуры",
    "keywords": ["список ключевых слов", "или ключевых фраз", "для этой статьи", "потенциально повторяющихся в других статьях по этой теме", "в формате массива JSON", "не менее 5", "не более 10", "на русском языке"],
    "summary": "аннотация, которую ты предлагаешь для этой статьи, не менее 100, не более 150 слов на русском языке",
    }}