script: write.py
prompts:
  embed:
    window_size: 0
    max_samples: 20
    model: snowflake-arctic-embed2:latest
  write:
    model: deepseek-r1:32b
    max_tokens: 32768
    template: |
      Напиши для обзорной статьи один раздел под названием:

      {section}

      Раздел, который нужно написать - первый не заполненный в следующей структуре статьи (до маркера <<ИНСТРУКЦИИ>>):

      {draft}

      <<ИНСТРУКЦИИ>>

      Раздел может использовать информацию из приведённых ниже отрывков исходных статей (до маркера <<ИНСТРУКЦИИ>>):

      {sources}

      <<ИНСТРУКЦИИ>>

      Нужно использовать информацию из приведённых выше отрывков исходных статей, но повторять предложения или фразы из них нельзя.

      Раздел находится в следующей структуре разделов обзорной статьи, от более общих к частным:

      {plan}

      Название раздела в этой структуре:

      {section}

      Напиши текст раздела - не менее 500 и не более 1000 слов и только на русском языке, не допускай китайского или английского.
      
      Не повторяй заголовок раздела и вообще не добавляй заголовков.

      Старайся детально и с указанием фактов раскрыть тему названного раздела, не переходя к другим темам и не погружаясь в них.

      Приводи конкретные и детальные примеры из исходных статей. Не пиши общие слова, и особенно не повторяй то, что сказано в других разделах обзора.
      
      Старайся передать упомянутые в источниках особенности, а также проанализировать взаимосвязи фактов между источниками.

      Для каждого факта или мнения в тексте проставь в квадратных скобках только номер источника, из которого получена эта информация.

      Ссылаться можно только на те источники, которые указаны в запросе, используя их номера, не указывая фамилию и год.
      
      Во всём тексте твоего ответа на один источник нужно указывать ссылку только в одном месте, которое лучше всего подходит.

      Напиши текст раздела - не менее 500 и не более 1000 слов и только на русском языке, не допускай китайского или английского.
      